### ISSUE TITLE
No ANSI encoding support

### ISSUE THREAD

**Issue by ashutoshns** [HyperSine/how-does-MobaXterm-encrypt-password#3]
Gives me an error:
```
Traceback (most recent call last):
  File "./MobaDecrypt.py", line 126, in <module>
    cipher = MobaXtermCrypto(sys.argv[1].encode('ansi'), sys.argv[2].encode('ansi') , sys.argv[3].encode('ansi'))
LookupError: unknown encoding: ansi
```
Also checking here: https://docs.python.org/2/library/codecs.html#standard-encodings
I don't see any ansi standard encoding

**Comment by HyperSine** [comment]
The first line of my python scripts is 
```
#!/usr/bin/env python3
```

So, you should use python3 rather than python2.

**Comment by lucache2000** [comment]
Even with python3 doesn't work. Python3 doesn't have ansi encoding. To fix replace all **ansi** with **utf_8** in MobaXtermCipher.py and it will work perfectly.

**Comment by ashutoshns** [comment]
Ah yes this seems to be related to linux. Works fine on windows. Replacing `ansi` with `cp1252` works as well.
